"""Version identifiers kept separate from historical regression cases."""

MODEL_VERSION = "0.3.0"
OPTIMIZATION_MODEL_VERSION = "0.3.0"
OPTIMIZATION_CASE_VERSION = "golden-v3"
SCENARIO_MODEL_VERSION = "0.2.0"
SCENARIO_CASE_VERSION = "golden-v2"
DATASET_VERSION = "demo-v1"
BASELINE_MODEL_VERSION = "0.1.0"
BASELINE_CASE_VERSION = "golden-v1"
CASE_VERSION = OPTIMIZATION_CASE_VERSION
