"""Central metric glossary used by documentation and Streamlit help controls."""
from __future__ import annotations
from dataclasses import dataclass

@dataclass(frozen=True)
class MetricDefinition:
    metric_id:str; label:str; short_description:str; unit:str; why_it_matters:str; calculation:str; interpretation:str; relationships:tuple[str,...]=(); caveats:str=""

def _m(i,l,d,u,w,c,it,r=(),cv=""):return MetricDefinition(i,l,d,u,w,c,it,r,cv)

METRICS={
"annual_load":_m("annual_load","Annual load","Electricity consumed by the site over one year.","MWh/year","It sets the scale of the energy problem.","Sum of hourly load energy.","Higher load generally increases grid purchases unless onsite supply also grows.",( "grid_import","self_sufficiency_ratio")),
"pv_capacity":_m("pv_capacity","PV capacity","Installed peak photovoltaic power.","kW","It determines the scale of available solar generation.","Capacity multiplied by hourly capacity factor.","More PV usually reduces imports but can increase exports and CAPEX.",( "pv_generation","grid_import","grid_export","pv_capex")),
"pv_generation":_m("pv_generation","PV generation","Electricity produced by PV.","MWh/year","It is the renewable energy available for load, storage or export.","PV capacity × hourly capacity factor, summed annually.","It rises linearly with PV capacity for a fixed profile.",( "pv_capacity","pv_self_consumption","grid_export")),
"pv_self_consumption":_m("pv_self_consumption","PV self-consumption","PV electricity retained onsite rather than exported.","MWh/year","Onsite use usually avoids higher-priced imports.","PV generation − PV export.","It can rise with better load coincidence or storage.",( "self_consumption_ratio","grid_export","battery_charge")),
"self_consumption_ratio":_m("self_consumption_ratio","PV self-consumption ratio","Share of PV generation kept onsite.","%","It indicates how much PV is used locally rather than exported.","PV self-consumption / PV generation.","High PV oversizing can reduce it; storage can increase it.",( "pv_self_consumption","pv_generation","grid_export","optimal_battery"),"It is not the same as self-sufficiency."),
"self_sufficiency_ratio":_m("self_sufficiency_ratio","Self-sufficiency ratio","Share of site load not supplied by the grid.","%","It measures dependence on grid electricity.","(Load − grid import) / load.","Higher values mean less grid dependence.",( "annual_load","grid_import","pv_generation"),"It is not the same as PV self-consumption."),
"battery_energy_capacity":_m("battery_energy_capacity","Battery energy capacity","Usable storage-size decision expressed as nominal energy capacity.","kWh","It controls how much energy can be shifted between hours.","Optimization decision constrained by SOC limits.","More capacity can increase PV utilization but also CAPEX.",( "battery_power_capacity","soc","battery_capex","battery_losses")),
"battery_power_capacity":_m("battery_power_capacity","Battery power capacity","Maximum AC charge/discharge rate.","kW","It controls how quickly energy can be shifted.","Hourly charge/discharge cannot exceed optimized power.","High energy with low power may be slow to use.",( "battery_energy_capacity","battery_charge","battery_discharge")),
"battery_charge":_m("battery_charge","Battery charge","PV energy sent to storage on the AC side.","MWh/year","It quantifies PV shifted in time instead of exported.","Sum of hourly PV-to-battery energy.","More charging can raise onsite PV use but creates conversion losses.",( "pv_self_consumption","battery_losses","soc")),
"battery_discharge":_m("battery_discharge","Battery discharge","AC energy delivered from storage to site load.","MWh/year","It reduces grid imports during deficit hours.","Sum of hourly battery-to-load energy.","It cannot exceed power and stored-energy limits.",( "grid_import","soc","battery_losses")),
"battery_losses":_m("battery_losses","Battery losses","Energy lost through charge/discharge inefficiency.","MWh/year","Losses reduce the net benefit of storage.","Charge×(1−ηc)+Discharge×(1/ηd−1).","Lower efficiencies increase losses.",( "battery_charge","battery_discharge","soc")),
"soc":_m("soc","State of charge (SOC)","Energy stored in the battery at a point in time.","kWh","It determines whether storage can absorb or deliver energy.","Previous SOC + ηc×charge − discharge/ηd.","SOC must remain between configured minimum and maximum limits.",( "battery_energy_capacity","battery_charge","battery_discharge")),
"grid_import":_m("grid_import","Grid import","Electricity purchased from the grid.","MWh/year","It drives purchase cost and modeled operational emissions.","Residual load after PV and battery discharge.","Lower imports generally reduce cost and emissions.",( "baseline_cost","scenario_emissions","self_sufficiency_ratio")),
"grid_export":_m("grid_export","Grid export","PV electricity exported after onsite use and charging.","MWh/year","It earns export revenue but is typically less valuable than avoided imports.","Residual PV after PV-to-load and PV-to-battery.","More PV can increase exports once onsite demand is saturated.",( "export_revenue","pv_generation","self_consumption_ratio")),
"pv_capex":_m("pv_capex","PV CAPEX","Upfront PV investment.","€","It is a major sizing driver.","PV capacity × PV CAPEX rate.","Higher PV CAPEX generally reduces optimal PV.",( "pv_capacity","annualized_capex","npv")),
"battery_capex":_m("battery_capex","Battery CAPEX","Upfront battery energy and power investment.","€","It determines whether shifting PV is worth its investment cost.","Energy kWh×€/kWh + power kW×€/kW.","High CAPEX can make optimal storage zero.",( "battery_energy_capacity","battery_power_capacity","npv")),
"opex":_m("opex","OPEX","Recurring annual operation and maintenance cost.","€/year","Ignoring OPEX would overstate technology value.","Installed capacity × configured annual OPEX rate.","Higher OPEX makes the technology less attractive.",( "scenario_cost","npv")),
"annualized_capex":_m("annualized_capex","Annualized CAPEX","Equivalent yearly cost of upfront investment.","€/year","It places capital costs in the same units as annual operating costs.","CAPEX × CRF.","It rises with CAPEX and usually with WACC.",( "crf","wacc","scenario_cost")),
"crf":_m("crf","Capital recovery factor (CRF)","Factor converting present investment into equivalent annual cost.","1/year","It links financing and lifetime to annualized CAPEX.","r(1+r)^n / ((1+r)^n−1).","Higher WACC generally raises CRF; longer life lowers it.",( "wacc","annualized_capex")),
"wacc":_m("wacc","WACC","Discount rate representing weighted cost of capital.","%","It affects annualized CAPEX and NPV.","User assumption used in CRF and discounting.","Higher WACC tends to penalize capital-intensive options.",( "crf","annualized_capex","npv"),"Synthetic screening assumption, not company-specific financing advice."),
"baseline_cost":_m("baseline_cost","Baseline annual cost","Grid-electricity cost before onsite investment.","€/year","It is the economic reference for savings.","Sum of hourly load × import price.","Higher baseline cost can make onsite investment more valuable.",( "annual_saving","scenario_cost","grid_import")),
"scenario_cost":_m("scenario_cost","Total annualized system cost","Annualized technologies plus net grid cost.","€/year","It is the optimizer objective.","PV annualized + battery annualized + purchases − export revenue.","Lower is economically better under the stated model boundary.",( "annualized_capex","baseline_cost","annual_saving")),
"annual_saving":_m("annual_saving","Annual equivalent saving","Baseline annual cost minus optimized annualized system cost.","€/year","It shows equivalent yearly economic improvement.","Baseline cost − scenario annualized cost.","Positive means the optimized system is cheaper on an annualized basis.",( "baseline_cost","scenario_cost","npv")),
"export_revenue":_m("export_revenue","Export revenue","Income assigned to exported PV electricity.","€/year","It changes the value of PV beyond onsite consumption.","Exported MWh × export price.","Higher export price can support more PV and reduce storage value.",( "grid_export","export_price","scenario_cost")),
"npv":_m("npv","Net present value (NPV)","Discounted project value after upfront CAPEX.","€","It tests whether discounted operating benefits exceed investment under assumptions.","−Initial CAPEX + discounted annual operating cash flows.","Positive NPV means modeled discounted benefits exceed CAPEX.",( "wacc","annual_saving","payback"),"Screening NPV excludes replacement, degradation, taxes and salvage value."),
"payback":_m("payback","Simple payback","Years of constant net operating savings needed to recover CAPEX.","years","It gives an intuitive investment-recovery view.","Initial CAPEX / annual net operating savings.","Shorter is generally preferred, but payback ignores discounting.",( "npv","annual_saving")),
"grid_emission_factor":_m("grid_emission_factor","Grid emission factor","CO₂ intensity assigned to imported electricity.","kgCO₂/MWh","It translates grid imports into operational emissions.","Explicit factor × imported MWh.","Higher factor increases absolute emissions for the same imports.",( "baseline_emissions","scenario_emissions","carbon_target")),
"baseline_emissions":_m("baseline_emissions","Baseline emissions","Grid-related emissions before onsite investment.","tCO₂/year","It is the reference for carbon targets.","Baseline imports × grid emission factor.","It scales with load and emission factor.",( "grid_emission_factor","co2_reduction","carbon_target")),
"scenario_emissions":_m("scenario_emissions","Scenario emissions","Grid-related emissions after optimization.","tCO₂/year","It determines whether carbon targets are met.","Optimized grid imports × grid emission factor.","Lower imports reduce emissions in this accounting method.",( "grid_import","co2_reduction","carbon_target"),"Exports receive no CO₂ credit."),
"co2_reduction":_m("co2_reduction","Absolute CO₂ reduction","Emissions avoided versus baseline.","tCO₂/year","It quantifies the modeled climate effect.","Baseline emissions − scenario emissions.","Positive values mean lower emissions.",( "baseline_emissions","scenario_emissions","abatement_cost")),
"co2_reduction_fraction":_m("co2_reduction_fraction","CO₂ reduction","Fractional emissions reduction versus baseline.","%","It is compared with the carbon target.","(Baseline−scenario)/baseline.","Higher values indicate deeper modeled decarbonization.",( "carbon_target","binding_carbon_constraint")),
"abatement_cost":_m("abatement_cost","Abatement cost","Incremental annualized cost per tonne of CO₂ avoided.","€/tCO₂","It combines climate and economic outcomes.","(Scenario annualized cost−baseline cost)/avoided tCO₂.","Negative means emissions fall while annualized cost also falls.",( "co2_reduction","scenario_cost","baseline_cost")),
"objective_function":_m("objective_function","Objective function","Quantity minimized by the LP.","€/year","It defines what the model considers economically best.","Annualized PV+battery + grid purchases − export revenue.","The economic optimum is the feasible solution with lowest objective.",( "economic_optimum","scenario_cost")),
"economic_optimum":_m("economic_optimum","Economic optimum","Lowest-cost feasible system without additional carbon requirement.","—","It is the reference for binding carbon constraints.","Solve LP with carbon target zero.","It may already reduce emissions if PV/storage are economical.",( "objective_function","carbon_target","binding_carbon_constraint")),
"carbon_target":_m("carbon_target","Carbon target","Minimum required CO₂ reduction versus baseline.","%","It quantifies the design consequence of stricter decarbonization.","Scenario CO₂ ≤ (1−target)×baseline CO₂.","Higher targets shrink the feasible set and can raise cost.",( "scenario_emissions","binding_carbon_constraint","infeasible_scenario")),
"binding_carbon_constraint":_m("binding_carbon_constraint","Binding carbon constraint","Whether optimized emissions sit at the allowed limit.","yes/no","It shows whether carbon policy is actively shaping design.","Compare optimized emissions with allowed maximum within tolerance.","Binding means the target changes or limits the optimum.",( "carbon_target","economic_optimum","scenario_emissions")),
"optimal_pv":_m("optimal_pv","Optimal PV","PV capacity selected by the optimizer.","kW","It is a central sizing output.","LP capacity decision at optimum.","It changes with load, price, CAPEX, WACC, export value and carbon target.",( "pv_capacity","scenario_cost","carbon_target")),
"optimal_battery":_m("optimal_battery","Optimal battery","Battery energy and power selected by the optimizer.","kWh / kW","It shows whether shifting surplus PV is worth storage cost.","LP capacity decisions at optimum.","Zero means storage adds insufficient value under current assumptions.",( "battery_energy_capacity","battery_power_capacity","battery_capex")),
"infeasible_scenario":_m("infeasible_scenario","Infeasible scenario","A case for which no physical solution satisfies all constraints.","—","It distinguishes impossible targets from solver errors.","HiGHS proves the feasible set is empty.","Can occur when carbon target exceeds what bounds allow.",( "carbon_target",)),
"import_price_multiplier":_m("import_price_multiplier","Import price multiplier","Multiplier applied to the synthetic hourly purchase-price profile.","×","It tests higher/lower price environments while preserving hourly shape.","Hourly import price = demo price × multiplier.","Higher prices generally increase onsite-generation value.",( "baseline_cost","grid_import","optimal_pv","optimal_battery"),"It is a sensitivity assumption, not a forecast."),
"export_price":_m("export_price","Export price","Value received per MWh exported.","€/MWh","It changes the trade-off between onsite use, storage and export.","Export revenue = export MWh × price.","Higher export value can support more PV but reduce storage value.",( "export_revenue","grid_export","optimal_pv","optimal_battery"),"Must remain below every import price in the LP."),
"pv_capex_rate":_m("pv_capex_rate","PV CAPEX rate","Upfront PV investment per installed kW.","€/kW","It is a primary PV sizing driver.","PV CAPEX = kW × €/kW.","Higher values generally reduce optimal PV.",( "pv_capex","optimal_pv","annualized_capex"),"Demo value is synthetic until Iteration 5."),
"pv_opex_rate":_m("pv_opex_rate","PV OPEX rate","Annual PV operating cost per kW.","€/kW-year","Recurring cost affects PV economics.","PV OPEX = kW × rate.","Higher OPEX makes PV less attractive.",( "opex","optimal_pv","scenario_cost")),
"pv_lifetime":_m("pv_lifetime","PV lifetime","Economic lifetime used to annualize PV CAPEX.","years","It affects CRF.","PV CRF uses WACC and lifetime.","Longer lifetime generally lowers annualized CAPEX.",( "crf","annualized_capex","optimal_pv")),
"battery_energy_capex_rate":_m("battery_energy_capex_rate","Battery energy CAPEX rate","Investment per kWh of energy capacity.","€/kWh","It controls cost of shifting more energy.","Energy CAPEX = optimized kWh × rate.","Lower rate can make storage enter the optimum.",( "battery_capex","battery_energy_capacity","optimal_battery")),
"battery_power_capex_rate":_m("battery_power_capex_rate","Battery power CAPEX rate","Investment per kW of battery power.","€/kW","It prices how fast storage can charge/discharge.","Power CAPEX = optimized kW × rate.","Higher rate can favor lower optimized power.",( "battery_capex","battery_power_capacity","optimal_battery")),
"battery_charge_efficiency":_m("battery_charge_efficiency","Charge efficiency","Fraction of AC charging energy retained in SOC.","%","Charging losses reduce storage value.","SOC increase = AC charge × efficiency.","Lower efficiency raises losses.",( "battery_charge","battery_losses","soc","optimal_battery")),
"battery_discharge_efficiency":_m("battery_discharge_efficiency","Discharge efficiency","Efficiency linking stored withdrawal to AC delivery.","%","Discharge losses reduce useful storage output.","SOC decrease = AC discharge / efficiency.","Lower efficiency raises losses.",( "battery_discharge","battery_losses","soc","optimal_battery")),
"soc_min_fraction":_m("soc_min_fraction","Minimum SOC","Lowest allowed SOC as fraction of battery energy.","%","It limits usable depth.","SOC ≥ fraction × energy capacity.","Higher minimum SOC reduces usable energy.",( "soc","battery_energy_capacity","optimal_battery")),
"soc_max_fraction":_m("soc_max_fraction","Maximum SOC","Highest allowed SOC as fraction of battery energy.","%","It limits usable storage headroom.","SOC ≤ fraction × energy capacity.","Lower maximum SOC reduces usable energy.",( "soc","battery_energy_capacity","optimal_battery")),
"max_pv_capacity":_m("max_pv_capacity","Maximum PV capacity","Configurable site/model upper bound on PV.","kW","It can determine feasibility and represent space/interconnection limits.","0≤PV≤maximum.","A binding max means more PV is unavailable in the model.",( "optimal_pv","carbon_target","infeasible_scenario"),"Model bound, not universal physical limit."),
"max_battery_energy":_m("max_battery_energy","Maximum battery energy","Upper bound on storage energy capacity.","kWh","It limits energy shifting and can affect feasibility.","0≤battery energy≤maximum.","A binding bound means more storage energy would otherwise be valued.",( "optimal_battery","battery_energy_capacity","infeasible_scenario"),"Model bound, not universal limit."),
"max_battery_power":_m("max_battery_power","Maximum battery power","Upper bound on storage charge/discharge power.","kW","It limits rate of energy shifting.","0≤battery power≤maximum.","A low limit can constrain storage usefulness.",( "optimal_battery","battery_power_capacity","infeasible_scenario"),"Model bound, not universal limit."),
"project_life":_m("project_life","Project life","Horizon used for simplified NPV.","years","It determines how many operating cash flows are discounted.","NPV discounts annual cash flow across selected years.","Longer life can increase NPV when cash flow is positive.",( "npv","payback","wacc"),"Current model excludes replacements and salvage value."),
"battery_lifetime":_m("battery_lifetime","Battery lifetime","Economic life used to annualize storage CAPEX.","years","It sets battery CRF.","Battery CRF uses WACC and lifetime.","Longer life lowers annualized storage burden, all else equal.",( "crf","annualized_capex","optimal_battery","project_life"),"No degradation/replacement is modeled."),
"average_import_price":_m("average_import_price","Average import price","Arithmetic average of the hourly purchase-price series.","€/MWh","It orients the user to the price environment, though optimization uses every hour.","Mean of hourly import prices after multiplier.","Higher averages often increase value of avoided purchases, but timing matters.",( "import_price_multiplier","baseline_cost","grid_import"),"It does not replace hourly prices in the LP."),
"initial_capex":_m("initial_capex","Total initial CAPEX","Upfront PV plus battery investment.","€","It shows initial capital requirement separately from annualized cost.","PV CAPEX + battery energy CAPEX + battery power CAPEX.","Higher CAPEX can still be attractive if lifetime savings justify it.",( "pv_capex","battery_capex","annualized_capex","npv")),
"solver_status":_m("solver_status","Solver status","Normalized optimization outcome.","—","It distinguishes successful, infeasible, unbounded and failed runs.","Mapped from HiGHS result status.","Only optimal solutions should be interpreted economically.",( "infeasible_scenario",)),
}

def get_metric(metric_id:str)->MetricDefinition:
    try:return METRICS[metric_id]
    except KeyError as e:raise KeyError(f"Unknown metric_id: {metric_id}") from e

def validate_metric_registry()->None:
    for metric_id,m in METRICS.items():
        if m.metric_id!=metric_id:raise ValueError(f"Metric key/id mismatch: {metric_id}")
        required=(m.label,m.short_description,m.unit,m.why_it_matters,m.calculation,m.interpretation)
        if any(not x.strip() for x in required):raise ValueError(f"Metric {metric_id} has an empty required field.")
        missing=set(m.relationships)-set(METRICS)
        if missing:raise ValueError(f"Metric {metric_id} references unknown metrics: {sorted(missing)}")
