"""Deterministic junior-engineer learning content for OptiDecarb v1.2."""
from __future__ import annotations
from .models import DecisionStage, IndustryCase, ProfessionalTerm, RolePerspective

PROFESSIONAL_TERMS = (
    ProfessionalTerm("screening", "Screening", "Screening", "A quick first assessment used to decide whether an idea deserves more study.", "Early project assessment before detailed engineering.", "This screening suggests that solar deserves a closer study.", "FOUNDATION"),
    ProfessionalTerm("prefeasibility", "Pre-feasibility", "Pre-feasibility study", "An early structured study that is more detailed than a quick screening, but not ready for investment approval.", "Project development before detailed feasibility and engineering.", "The project is still at pre-feasibility stage.", "FOUNDATION", "prefactibilidad"),
    ProfessionalTerm("feasibility", "Feasibility", "Feasibility study", "A more detailed technical and economic study used before a major investment decision.", "Project development after pre-feasibility.", "We need site data before moving to feasibility.", "INTERMEDIATE"),
    ProfessionalTerm("feed", "FEED", "Front-End Engineering Design", "Engineering work that defines the project before detailed design and construction.", "Large industrial projects before EPC execution.", "The team may complete FEED before tendering the EPC package.", "ADVANCED", "ingeniería básica / diseño previo"),
    ProfessionalTerm("epc", "EPC", "Engineering, Procurement and Construction", "A contractor that can design the project, buy the equipment and build the installation.", "Turnkey industrial energy projects.", "We should request budgetary EPC quotations.", "INTERMEDIATE", "ingeniería, compras y construcción"),
    ProfessionalTerm("owners_engineer", "Owner's engineer", "Owner's engineer", "An engineer or consultancy that protects the project owner's technical interests.", "Independent review during development, procurement and construction.", "The owner's engineer reviewed the EPC proposal.", "ADVANCED"),
    ProfessionalTerm("due_diligence", "Due diligence", "Technical due diligence", "An independent check of important project risks before an investment or transaction.", "Financing, acquisition and investment review.", "The lender requested technical due diligence.", "ADVANCED", "revisión técnica previa"),
    ProfessionalTerm("ppa", "PPA", "Power Purchase Agreement", "A contract to buy or sell electricity under agreed conditions for a defined period.", "Corporate renewable procurement.", "The factory is comparing a PPA with onsite PV.", "INTERMEDIATE", "contrato de compraventa de energía"),
    ProfessionalTerm("offtake", "Offtake", "Energy offtake", "The commercial arrangement for who buys the electricity produced by a project.", "Renewable project commercial structures.", "The project needs a clear offtake arrangement.", "ADVANCED"),
    ProfessionalTerm("curtailment", "Curtailment", "Generation curtailment", "Available generation that is intentionally reduced because it cannot be used or exported.", "Renewable projects with grid or export limits.", "Export limits may cause PV curtailment.", "INTERMEDIATE", "limitación / vertido de generación"),
    ProfessionalTerm("tariff", "Tariff", "Electricity tariff", "The commercial structure used to calculate what a customer pays for electricity.", "Electricity contracts and bills.", "We need the real tariff before trusting the savings estimate.", "FOUNDATION", "tarifa eléctrica"),
    ProfessionalTerm("demand_charge", "Demand charge", "Demand charge", "A bill component linked to peak or contracted power rather than total energy.", "Industrial tariffs in some markets.", "A battery may create value by reducing a demand charge.", "ADVANCED", "cargo por potencia / demanda"),
    ProfessionalTerm("quotation", "Quotation", "Supplier quotation", "A supplier's commercial offer for a defined scope of equipment or work.", "Procurement and feasibility.", "Public CAPEX benchmarks should later be replaced by supplier quotations.", "FOUNDATION", "oferta / presupuesto"),
    ProfessionalTerm("site_survey", "Site survey", "Site survey", "A visit or technical inspection used to confirm real site conditions.", "Before detailed design.", "A site survey should confirm roof access and electrical constraints.", "FOUNDATION", "visita / inspección de emplazamiento"),
    ProfessionalTerm("permitting", "Permitting", "Permitting", "The approvals and permits required before a project can be built and operated.", "Project development.", "Permitting requirements must be checked before construction.", "INTERMEDIATE", "tramitación de permisos"),
    ProfessionalTerm("commissioning", "Commissioning", "Commissioning", "Final testing and start-up of equipment before normal operation.", "End of construction and handover.", "The battery is tested during commissioning.", "INTERMEDIATE", "puesta en marcha"),
    ProfessionalTerm("om", "O&M", "Operations and Maintenance", "The work needed to operate and maintain equipment after construction.", "Asset operation.", "The EPC quotation should clarify the O&M scope.", "INTERMEDIATE", "operación y mantenimiento"),
    ProfessionalTerm("business_case", "Business case", "Business case", "The structured reason for spending money on a project, including benefits, costs, risks and alternatives.", "Investment decisions.", "Finance will challenge the assumptions in the business case.", "FOUNDATION"),
    ProfessionalTerm("downside", "Downside scenario", "Downside scenario", "A deliberately less favourable case used to see how a project performs if important assumptions worsen.", "Finance and risk review.", "Let's test a downside scenario with lower electricity prices.", "INTERMEDIATE"),
    ProfessionalTerm("robustness", "Robustness", "Robustness", "How well a conclusion holds when reasonable assumptions change.", "Sensitivity and decision-making.", "The recommendation is more robust if it survives several sensitivities.", "INTERMEDIATE"),
    ProfessionalTerm("assumptions_log", "Assumptions log", "Assumptions log", "A simple record of important assumptions, their source and why they were used.", "Engineering studies and project governance.", "Update the assumptions log when a supplier quote replaces a benchmark.", "FOUNDATION"),
)
PROFESSIONAL_TERMS_BY_ID = {x.term_id: x for x in PROFESSIONAL_TERMS}

ROLE_PERSPECTIVES = (
    RolePerspective("operations", "Operations", ("Will production be interrupted?", "Are shutdowns required?", "What operational constraints are missing?", "Will reliability change?"), "Operations protects production continuity and safe operation."),
    RolePerspective("finance", "Finance", ("How much CAPEX is required?", "What are NPV and payback?", "Which assumptions drive value?", "What happens in a downside scenario?"), "Finance cares about value, risk and uncertainty, not only technical performance."),
    RolePerspective("sustainability", "Sustainability", ("What is the emissions baseline?", "Which emission factor is used?", "Is the source traceable?", "Can the result be audited?"), "Sustainability needs a defensible carbon calculation and clear boundaries."),
    RolePerspective("maintenance", "Maintenance", ("What new equipment will we own?", "Who services it?", "What warranty applies?", "What spare parts or skills are needed?"), "Maintenance thinks about the asset after construction."),
    RolePerspective("management", "Management", ("What decision is needed?", "What is the expected benefit?", "What is the main risk?", "What should happen next?"), "Management normally needs a short decision-ready message, not every hourly variable."),
)

CHECKLISTS = {
    "before_modelling": ("Define the real question.", "Check data source and units.", "Check timestamps and missing values.", "Document assumptions.", "Confirm what is outside model scope."),
    "before_trusting": ("Does the result make physical sense?", "Run simple sanity checks.", "Check whether the optimum is near a model bound.", "Test important sensitivities.", "List missing real-world constraints."),
    "before_management": ("Explain the result in 30 seconds.", "State the main assumption.", "State the main risk.", "Avoid false precision.", "Recommend one clear next step."),
    "before_suppliers": ("Define the required scope.", "Ask what is included and excluded.", "Request performance and warranty data.", "Check CAPEX and O&M assumptions.", "Compare quotations on the same basis."),
    "before_co2_claim": ("Define the baseline.", "Record the emission-factor source.", "Check units and boundaries.", "Explain treatment of exports.", "Avoid claiming more than the model supports."),
}

GOOD_JUNIOR_QUESTIONS = (
    "Where did this number come from?", "Is it measured, derived or assumed?", "What period does it cover?", "Are the units correct?",
    "Are any hours missing or duplicated?", "Is the result close to a model limit?", "Which assumption matters most?", "What could invalidate this conclusion?", "What data should we ask for next?",
)
WORK_PHRASES = (
    "Based on the available data...", "Under the current assumptions...", "The main uncertainty is...", "We would need to validate...",
    "This should be treated as a screening result.", "I would not conclude that yet because...", "The model does not currently include...", "The next step would be...", "We do not yet have enough information to conclude that.",
)
DECISION_STAGES = (
    DecisionStage("Curiosity", "A question or opportunity has been identified.", "Define the problem and decide whether to investigate."),
    DecisionStage("Screening", "A quick first assessment using limited but explicit data.", "Direction, order of magnitude and key uncertainties."),
    DecisionStage("Pre-feasibility", "A structured early study with better data and sensitivity analysis.", "Promising configuration and evidence needed for the next stage."),
    DecisionStage("Feasibility", "A more detailed technical and economic study.", "A stronger investment case with site-specific inputs."),
    DecisionStage("Budget quotation", "Suppliers provide preliminary project pricing and scope.", "Project-specific CAPEX and commercial assumptions."),
    DecisionStage("Investment approval", "The company decides whether to commit capital.", "Approved business case and risk acceptance."),
    DecisionStage("Detailed engineering / EPC", "The project is designed and prepared for construction.", "Buildable design, equipment and execution plan."),
    DecisionStage("Construction", "The project is physically built.", "Installed equipment and completed works."),
    DecisionStage("Commissioning", "The installed system is tested before normal use.", "Verified safe operation and handover."),
    DecisionStage("Operation", "The asset is operated and maintained.", "Measured performance, maintenance and continuous improvement."),
)

def _case(case_id, title, situation, info, question, options, correct, junior, incomplete, better, why, checks, data, lesson):
    feedback = tuple("This option is too general, unsupported or skips an important engineering check." for _ in range(len(options) - 1))
    return IndustryCase(case_id, title, situation, tuple(info), question, tuple(options), correct, junior, incomplete, better, why, feedback, tuple(checks), tuple(data), lesson)

INDUSTRY_CASES = (
    _case("impossible_peak", "Impossible peak demand", "A plant reports 15 GWh/year but only 0.9 MW peak demand.", ["Annual energy: 15,000 MWh", "Peak: 0.9 MW"], "Does this make sense?", ["Yes", "No — check the data", "Not enough information"], "No — check the data", "The numbers look reasonable.", "15,000/8,760 = 1.71 MW average load, which cannot exceed the peak.", "The data are inconsistent; check units, period and peak definition before modelling.", "Average power cannot be above peak power.", ["Calculate average load", "Check units and time period"], ["Original interval data", "Peak-demand definition"], "Do an order-of-magnitude check before building a detailed model."),
    _case("missing_hours", "Missing hourly data", "A load file contains 8,759 hourly rows.", ["Expected non-leap year: 8,760 hours", "Received: 8,759"], "What should you do?", ["Run anyway", "Find the missing timestamp", "Duplicate the last hour"], "Find the missing timestamp", "One hour will not matter.", "A missing hour breaks the exact time sequence and can distort energy, prices or battery SOC.", "Identify the missing timestamp and recover or document the missing value before solving.", "Never silently invent time-series data.", ["Check timestamp continuity", "Check timezone"], ["Original meter export", "Data-quality note"], "Time-series quality is part of engineering quality."),
    _case("supplier_40", "Supplier promises 40% savings", "A battery supplier claims its system will cut the electricity bill by 40%.", ["No baseline supplied", "No tariff supplied"], "Best first response?", ["Accept the claim", "Ask 40% of what, under which baseline and tariff?", "Reject all batteries"], "Ask 40% of what, under which baseline and tariff?", "The supplier is an expert, so the claim is probably correct.", "A percentage saving has little meaning without a baseline, tariff, dispatch strategy and system size.", "Ask for the calculation basis, power/energy rating, efficiency, degradation, warranty, CAPEX and avoided bill components.", "Commercial claims must be traceable to assumptions.", ["Define baseline", "Check tariff and dispatch"], ["Supplier model", "Tariff", "Technical datasheet"], "Challenge claims with specific technical questions rather than accepting or rejecting them emotionally."),
    _case("battery_zero", "Battery is zero", "The economic optimum selects PV but no battery.", ["Battery energy: 0 MWh", "PV: about 3 MWp"], "What can you conclude?", ["Batteries are useless", "The solver is wrong", "Battery is not cost-optimal under current assumptions"], "Battery is not cost-optimal under current assumptions", "Batteries are not economical.", "That statement is too general; the result depends on prices, CAPEX, losses and constraints.", "Under the current assumptions, storage is not selected in the economic optimum. It can become useful under different economics or stricter carbon targets.", "The conclusion is conditional, not universal.", ["Review battery CAPEX", "Check carbon constraints"], ["Supplier quotation", "Tariff/value streams"], "Use conditional engineering language."),
    _case("pv_bound", "PV optimum hits a limit", "The optimal PV capacity equals the maximum allowed by the model.", ["Optimal PV = model upper bound"], "What should you check?", ["Report it as exact optimum", "Test whether the bound is driving the solution", "Lower the result manually"], "Test whether the bound is driving the solution", "The optimum is exactly this capacity.", "The model may want more PV but is prevented by the chosen bound.", "Increase or justify the bound, then rerun sensitivity before interpreting the capacity as an unconstrained optimum.", "Model bounds can shape the answer.", ["Check active bounds", "Review physical space assumptions"], ["Roof/land area", "Grid/export limit"], "Always inspect whether an optimum is sitting on a model boundary."),
    _case("positive_npv", "Positive NPV, high uncertainty", "A screening gives positive NPV but uses proxy prices and benchmark CAPEX.", ["NPV > 0", "No site quote", "Wholesale-price proxy"], "Is the project ready for approval?", ["Yes", "No — validate key assumptions first", "NPV is useless"], "No — validate key assumptions first", "Positive NPV means build it.", "NPV is conditional on assumptions and this is still a screening model.", "Treat the result as evidence for further study, then validate tariff, site constraints, quotations and risks.", "Positive NPV supports study; it does not replace investment governance.", ["Run sensitivities", "Identify largest uncertainty"], ["Real tariff", "EPC quotations", "Site constraints"], "Economic metrics need context and maturity."),
    _case("carbon_binding", "40% carbon target becomes binding", "The economic optimum already cuts emissions by about 30.4%; a 40% target forces a different design.", ["Economic reduction ≈30.4%", "20% target non-binding", "40% target binding"], "Why does storage appear at 40%?", ["The solver likes batteries", "The stricter target changes the feasible solution", "Battery efficiency becomes 100%"], "The stricter target changes the feasible solution", "The model randomly adds a battery.", "The 40% constraint requires deeper reduction than the economic optimum can deliver unchanged.", "More PV creates more surplus; storage can shift some of it to reduce later grid imports and help meet the target.", "A binding constraint can change technology value.", ["Compare economic and constrained solutions", "Check target slack"], ["Carbon objective", "Operational constraints"], "Optimization results depend on both economics and constraints."),
    _case("answer_today", "Manager wants an answer today", "Your manager asks for a first estimate before real site data are available.", ["Public data available", "No plant tariff", "No site survey"], "What is a professional response?", ["Refuse to analyse anything", "Give a precise build recommendation", "Provide a screening with explicit assumptions and limits"], "Provide a screening with explicit assumptions and limits", "I can tell you exactly what to build today.", "Precision would create false confidence because key site data are missing.", "I can prepare an initial screening today, clearly label assumptions and identify the data needed before a real investment decision.", "Speed and professional humility can coexist.", ["Label proxies", "State confidence level"], ["Interval load", "Tariff", "Site information"], "A junior engineer can be useful without pretending uncertainty does not exist."),
)
INDUSTRY_CASES_BY_ID = {x.case_id: x for x in INDUSTRY_CASES}

def validate_industry_catalog() -> None:
    if len(INDUSTRY_CASES_BY_ID) != len(INDUSTRY_CASES): raise ValueError("Duplicate industry case id")
    if len(PROFESSIONAL_TERMS_BY_ID) != len(PROFESSIONAL_TERMS): raise ValueError("Duplicate professional term id")
    for case in INDUSTRY_CASES:
        if case.correct_option not in case.options or not case.why_correct or not case.better_answer: raise ValueError(case.case_id)
        if len(case.other_options_feedback) != len(case.options)-1: raise ValueError(case.case_id)
    for term in PROFESSIONAL_TERMS:
        if not all((term.full_name, term.easy_explanation, term.where_used, term.example_sentence)): raise ValueError(term.term_id)
